import { translate, route } from '../content/locale.mjs';
import { eyebrow, portrait, textLink } from '../components/ui.mjs';
import { breadcrumbs } from '../components/sections.mjs';

export default function about(lang='nl') {
  const t=translate(lang);
  return `<section class="about-hero section-space"><div class="container">${breadcrumbs(t('Over Lex','About Lex'),lang)}<div class="about-hero-grid"><div>${eyebrow(t('Over Lex','About Lex'))}<h1>${t('Ervaring aan beide kanten.','Experience on both sides.')}</h1><p class="large-paragraph">${t('Ik ben Lex de Lange. Als oud-militair en gebrevetteerd commando ken ik Defensie van binnenuit. Vanuit grote en kleine IT-bedrijven heb ik jarenlang met deze sector samengewerkt.','I’m Lex de Lange. As a former serviceman and qualified commando, I know Defence from the inside. I have also spent years working with the sector from within large and small IT companies.')}</p>${textLink(route('contact',lang),t('Laten we kennismaken','Let’s get acquainted'))}</div><figure class="portrait-frame portrait-frame--about"><div class="portrait-window">${portrait({eager:true})}</div></figure></div></div></section>
  <section class="biography section-space"><div class="container editorial-layout"><div>${eyebrow(t('Twee perspectieven','Two perspectives'))}<h2>${t('Van ervaring naar advies.','From experience to advice.')}</h2></div><div class="prose"><p class="large-paragraph">${t('Een bedrijf en een defensieorganisatie kijken niet altijd op dezelfde manier naar een vraagstuk. Ik help die perspectieven bij elkaar te brengen.','A company and a defence organisation may look at the same challenge in different ways. I help bring those perspectives together.')}</p><p>${t('Mijn militaire achtergrond vormt één kant van mijn ervaring. Ik ken de taal en de context van Defensie. De andere kant is mijn jarenlange samenwerking met de sector vanuit het bedrijfsleven.','My military background is one side of my experience. I know the language and context of Defence. The other is my long-standing work with the sector from the business side.')}</p><p>${t('Daardoor begrijp ik zowel de behoefte van een organisatie als de mogelijkheden en ambities van een bedrijf. Ik maak de vertaalslag tussen problemen en oplossingen, tussen verschillende niveaus in een organisatie en tussen mensen die elkaar nog niet vanzelfsprekend vinden.','That helps me understand both an organisation’s needs and a company’s capabilities and ambitions. I connect problems with solutions, different levels of an organisation, and people who might not otherwise meet.')}</p><p>${t('Met Bridge2Connect ondersteun ik bedrijven die zaken willen doen met deze bijzondere sector, maar daar wat hulp bij kunnen gebruiken. Het vertrekpunt is uw bedrijf en de vraag waarmee u rondloopt.','Through Bridge2Connect, I support companies that want to do business with this sector and could use some guidance. The starting point is your company and the question you want to work through.')}</p></div></div></section>
  <section class="quote-section"><div class="container"><blockquote>${t('“Ik ken de weg, spreek de taal en heb mijn netwerk binnen en rondom deze bijzondere sector.”','“I know my way around, speak the language and have a network within and around this distinctive sector.”')}</blockquote></div></section>
  <section class="principles section-space"><div class="container">${eyebrow(t('Wat u van mij mag verwachten','What you can expect'))}<div class="principle-grid">
    <article><h2>${t('Persoonlijke betrokkenheid','Personal involvement')}</h2><p>${t('Direct contact en aandacht voor uw bedrijf, uw ambities en de mensen met wie u wilt samenwerken.','Direct contact and attention to your company, your ambitions and the people you want to work with.')}</p></article>
    <article><h2>${t('Begrip van beide werelden','Understanding both worlds')}</h2><p>${t('Ervaring vanuit de militaire praktijk én het bedrijfsleven, om het gesprek mogelijk te maken en inhoud te geven.','Experience from military practice and business, helping make conversations possible and meaningful.')}</p></article>
    <article><h2>${t('Relevante verbindingen','Relevant connections')}</h2><p>${t('Contacten en partners die passen bij de vraag die u wilt oplossen. Niet de hoeveelheid namen, maar de relevantie telt.','Contacts and partners suited to the challenge you want to address. Relevance matters more than the size of a contact list.')}</p></article>
  </div></div></section>`;
}
