import { site } from '../content/site.mjs';
import { escape, safeUrl, eyebrow, icon, portrait } from '../components/ui.mjs';
import { breadcrumbs } from '../components/sections.mjs';

export default function contact() {
  const email = safeUrl(site.email, { email: true });
  const linkedIn = safeUrl(site.linkedIn);
  return `<section class="contact-page section-space"><div class="container">${breadcrumbs('Kennismaken')}<div class="contact-layout"><div class="contact-intro">${eyebrow('Laten we kennismaken')}<h1>Kennismaken<br>met Lex.</h1><p class="large-paragraph">Wilt u de sector verkennen, uw netwerk uitbreiden of een samenwerking verder brengen? Vertel waar u naartoe wilt.</p>
    <div class="contact-person">${portrait({ size: 'small', eager: true })}<div><h2>Lex de Lange</h2><p>Uw contactpersoon bij Bridge2Connect</p></div></div>
    <div class="contact-details">${email ? `<a href="${escape(email)}">${icon('mail')}<span>${escape(site.email)}</span></a>` : ''}${site.phone ? `<a href="tel:${escape(site.phone)}">${icon('phone')}<span>${escape(site.phoneDisplay || site.phone)}</span></a>` : ''}${linkedIn ? `<a href="${escape(linkedIn)}" target="_blank" rel="noopener noreferrer">${icon('diagonal')}<span>Lex op LinkedIn</span></a>` : ''}</div>
    ${!email ? '<div class="contact-pending"><span class="status-dot" aria-hidden="true"></span><p>De definitieve contactgegevens worden nog toegevoegd. U kunt uw bericht alvast opstellen en kopiëren; er wordt niets verstuurd.</p></div>' : '<p class="contact-note">Mail Lex rechtstreeks of stel via het formulier een e-mail op. U verzendt het bericht vervolgens zelf vanuit uw eigen mailprogramma.</p>'}
    <div class="contact-expectation"><h2>Een eerste gesprek gaat over</h2><p>${icon('check')}Uw bedrijf en uw aanbod</p><p>${icon('check')}Uw vraag over de sector</p><p>${icon('check')}Een mogelijke volgende stap</p></div>
  </div>
  <div class="contact-form-panel"><div class="form-title"><h2>Stel uw bericht op</h2></div><p>Een paar regels is genoeg om te beginnen.</p>
    <form id="contact-form" data-recipient="${escape(email ? site.email : '')}" aria-describedby="form-note" novalidate>
      <div class="form-row"><div class="field"><label for="name">Uw naam <span>*</span></label><input id="name" name="name" autocomplete="name" required maxlength="100" placeholder="Voor- en achternaam" aria-describedby="name-error"><span class="field-error" id="name-error"></span></div><div class="field"><label for="company">Bedrijf</label><input id="company" name="company" autocomplete="organization" maxlength="140" placeholder="Uw organisatie"></div></div>
      <div class="field"><label for="email">E-mailadres <span>*</span></label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254" placeholder="naam@bedrijf.nl" aria-describedby="email-error"><span class="field-error" id="email-error"></span></div>
      <div class="field"><label for="subject">Waar gaat uw vraag over?</label><select id="subject" name="subject"><option value="Een eerste kennismaking">Een eerste kennismaking</option><option>De sector begrijpen</option><option>De juiste mensen verbinden</option><option>Van vraag naar samenwerking</option><option>Een andere vraag</option></select></div>
      <div class="field"><label for="message">Uw vraag of bericht <span>*</span></label><textarea id="message" name="message" rows="5" required minlength="10" maxlength="3000" placeholder="Vertel kort wat uw bedrijf doet en waar u ondersteuning bij zoekt." aria-describedby="message-error"></textarea><span class="field-error" id="message-error"></span></div>
      <p class="form-note" id="form-note">Uw gegevens blijven in deze browser totdat u zelf mailt of het bericht kopieert. <a href="/privacy/">Meer over privacy</a>.</p>
      <button class="button button--primary form-submit" type="submit"><span>E-mail opstellen</span>${icon('arrow')}</button><span class="required-note">* Verplichte velden</span>
      <noscript><p>Voor het voorbereiden van een bericht is JavaScript nodig. ${email ? `U kunt rechtstreeks mailen naar <a href="${escape(email)}">${escape(site.email)}</a>.` : 'De contactgegevens worden nog toegevoegd.'}</p></noscript>
    </form>
  </div></div></div></section>
  <dialog class="message-dialog" id="message-dialog" aria-labelledby="message-heading" aria-describedby="message-explanation"><div class="dialog-inner"><button class="dialog-close" type="button" aria-label="Berichtvenster sluiten" data-close-dialog>${icon('close')}</button>${eyebrow('Uw bericht')}<h2 id="message-heading">Uw conceptbericht</h2><p id="message-explanation">Dit bericht is nog niet verstuurd. ${email ? 'Open uw mailprogramma of kopieer de tekst.' : 'Het e-mailadres van Lex moet nog worden toegevoegd. Kopieer de tekst om hem te bewaren.'}</p><label class="visually-hidden" for="prepared-message">Uw voorbereide bericht</label><textarea id="prepared-message" readonly rows="9" spellcheck="false"></textarea><div class="dialog-actions">${email ? `<a id="open-email" class="button button--primary" href="${escape(email)}"><span>Open in mailprogramma</span>${icon('mail')}</a>` : ''}<button class="button button--${email ? 'outline' : 'primary'}" id="copy-message" type="button"><span>Kopieer bericht</span>${icon('arrow')}</button></div><p class="copy-status" id="copy-status" role="status" aria-live="polite"></p></div></dialog>`;
}
