import { resolveContactDelivery } from '../content/contact-delivery.mjs';
import { deliveryControls, deliveryFeedback } from '../components/contact-delivery.mjs';
import { site } from '../content/site.mjs';
import { translate, route, subjectOptions } from '../content/locale.mjs';
import { escape, safeUrl, eyebrow, icon, portrait } from '../components/ui.mjs';
import { breadcrumbs } from '../components/sections.mjs';

export default function contact(lang='nl', deliveryOptions) {
  const delivery = resolveContactDelivery(deliveryOptions);
  const t=translate(lang), email=safeUrl(site.email,{email:true}), linkedIn=safeUrl(site.linkedIn);
  const options=subjectOptions(lang), topics=['intro','sectorinzicht','verbinding','samenwerking','other'];
  return `<section class="contact-page section-space"><div class="container">${breadcrumbs(t('Kennismaken','Get in touch'),lang)}<div class="contact-layout"><div class="contact-intro">${eyebrow(t('Laten we kennismaken','Let’s talk'))}<h1>${t('Kennismaken<br>met Lex.','Get in touch<br>with Lex.')}</h1><p class="large-paragraph">${t('Wilt u de sector verkennen, uw netwerk uitbreiden of een samenwerking verder brengen? Vertel waar u naartoe wilt.','Looking to explore the sector, broaden your network or develop a collaboration? Tell me what you have in mind.')}</p>
    <div class="contact-person">${portrait({size:'small',eager:true})}<div><h2>Lex de Lange</h2><p>${t('Uw contactpersoon','Your point of contact')}</p></div></div>
    <div class="contact-details">${email?`<a href="${escape(email)}">${icon('mail')}<span>${escape(site.email)}</span></a>`:''}${site.phone?`<a href="tel:${escape(site.phone)}">${icon('phone')}<span>${escape(site.phoneDisplay||site.phone)}</span></a>`:''}${linkedIn?`<a href="${escape(linkedIn)}" target="_blank" rel="noopener noreferrer">${icon('diagonal')}<span>LinkedIn</span></a>`:''}</div>
    <p class="contact-note">${delivery.enabled ? t('Stuur uw bericht via het formulier. U blijft op deze website.','Send your message using the form. You stay on this website.') : t('Mail rechtstreeks of stel met het formulier een e-mail op. U verzendt het bericht zelf vanuit uw eigen mailprogramma.','Email me directly or use the form to prepare a message. You send the email yourself from your own email application.')}</p>
    <div class="contact-expectation"><h2>${t('Een eerste gesprek gaat over','An initial conversation covers')}</h2><p>${icon('check')}${t('Uw bedrijf en uw aanbod','Your company and your offering')}</p><p>${icon('check')}${t('Uw vraag over de sector','Your question about the sector')}</p><p>${icon('check')}${t('Een mogelijke volgende stap','A possible next step')}</p></div></div>
    <div class="contact-form-panel"><div class="form-title"><h2>${delivery.enabled ? t('Stuur een bericht','Send a message') : t('Stel uw bericht op','Prepare your message')}</h2></div><p>${t('Een paar regels is genoeg om te beginnen.','A few lines are enough to get started.')}</p>
    <form id="contact-form" method="post" ${delivery.enabled ? `data-delivery="web3forms" data-access-key="${escape(delivery.accessKey)}" action="${delivery.endpoint}"` : ''} data-recipient="${escape(email?site.email:'')}" aria-describedby="form-note" novalidate><fieldset data-form-fields disabled>
    <div class="form-row"><div class="field"><label for="name">${t('Uw naam','Your name')} <span>*</span></label><input id="name" name="name" autocomplete="name" required maxlength="100" placeholder="${t('Voor- en achternaam','First and last name')}" aria-describedby="name-error"><span class="field-error" id="name-error"></span></div><div class="field"><label for="company">${t('Bedrijf','Company')}</label><input id="company" name="company" autocomplete="organization" maxlength="140" placeholder="${t('Uw organisatie','Your organisation')}"></div></div>
    <div class="field"><label for="email">${t('E-mailadres','Email address')} <span>*</span></label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254" placeholder="${t('naam@bedrijf.nl','name@company.com')}" aria-describedby="email-error"><span class="field-error" id="email-error"></span></div>
    <div class="field"><label for="subject">${t('Waar gaat uw vraag over?','What would you like to discuss?')}</label><select id="subject" name="subject">${options.map((item,i)=>`<option value="${escape(item.value)}" data-topic="${topics[i]}">${escape(item.label)}</option>`).join('')}</select></div>
    <div class="field"><label for="message">${t('Uw vraag of bericht','Your question or message')} <span>*</span></label><textarea id="message" name="message" rows="5" required minlength="10" maxlength="3000" placeholder="${t('Vertel kort wat uw bedrijf doet en waar u ondersteuning bij zoekt.','Tell me briefly what your company does and where you need support.')}" aria-describedby="message-error"></textarea><span class="field-error" id="message-error"></span></div>
${delivery.enabled ? deliveryControls(lang) : `    <p class="form-note" id="form-note">${t('Uw gegevens blijven in deze browser totdat u zelf mailt of het bericht kopieert.','Your details stay in this browser until you choose to email or copy the message.')} <a href="${route('privacy',lang)}">${t('Meer over privacy','More about privacy')}</a>.</p>`}
    <button class="button button--primary form-submit" type="submit"><span>${delivery.enabled ? t('Bericht versturen','Send message') : t('E-mail opstellen','Prepare email')}</span>${icon('arrow')}</button><span class="required-note">${t('* Verplichte velden','* Required fields')}</span>
    </fieldset>${delivery.enabled ? deliveryFeedback(lang) : ''}<noscript><p>${t('Voor het voorbereiden van een bericht is JavaScript nodig. U kunt rechtstreeks mailen naar','Preparing a message requires JavaScript. You can email directly at')} <a href="${escape(email)}">${escape(site.email)}</a>.</p></noscript></form></div></div></div></section>
${delivery.enabled ? '' : `    <dialog class="message-dialog" id="message-dialog" aria-labelledby="message-heading" aria-describedby="message-explanation"><div class="dialog-inner"><button class="dialog-close" type="button" aria-label="${t('Berichtvenster sluiten','Close message window')}" data-close-dialog>${icon('close')}</button>${eyebrow(t('Uw bericht','Your message'))}<h2 id="message-heading">${t('Uw conceptbericht','Your draft message')}</h2><p id="message-explanation">${t('Dit bericht is nog niet verstuurd. Open uw mailprogramma of kopieer de tekst.','This message has not been sent. Open your email application or copy the text.')}</p><label class="visually-hidden" for="prepared-message">${t('Uw voorbereide bericht','Your prepared message')}</label><textarea id="prepared-message" readonly rows="9" spellcheck="false"></textarea>
    <div class="dialog-actions">${email?`<a id="open-email" class="button button--primary" href="${escape(email)}"><span>${t('Open in mailprogramma','Open email application')}</span>${icon('mail')}</a>`:''}<button class="button button--outline" id="copy-message" type="button"><span>${t('Kopieer bericht','Copy message')}</span>${icon('arrow')}</button></div><p class="copy-status" id="copy-status" role="status" aria-live="polite"></p></div></dialog>`}`;
}
