import { translate, route, servicesFor } from '../content/locale.mjs';
import { escape, eyebrow, icon, textLink, editorialPhoto } from '../components/ui.mjs';
import { breadcrumbs, process } from '../components/sections.mjs';

export default function expertise(lang='nl') {
  const t=translate(lang), services=servicesFor(lang);
  return `<section class="page-intro section-space"><div class="container">${breadcrumbs('Expertise',lang)}${eyebrow('Expertise')}<div class="heading-grid page-heading"><h1>${t('Zaken doen met<br>Defensie & Veiligheid.','Working with<br>Defence & Security.')}</h1><p class="large-paragraph">${t('Ik help uw bedrijf de sector te begrijpen, relevante mensen te spreken en van een behoefte naar een passende oplossing te komen.','I help your company understand the sector, speak to relevant people and connect a real need with a suitable solution.')}</p></div><nav class="service-jumps" aria-label="${t('Expertisegebieden','Areas of expertise')}">${services.map(service=>`<a href="#${service.id}">${escape(service.title)}${icon('down')}</a>`).join('')}</nav></div></section>
  ${services.map(service=>`<section class="expertise-detail section-space" id="${service.id}"><div class="container detail-layout"><div class="detail-label">${eyebrow(service.title)}<blockquote>${escape(service.question)}</blockquote>${service.id==='sectorinzicht'?editorialPhoto('technology',lang,'expertise-context-image'):''}</div><div class="detail-content"><h2>${escape(service.heading)}</h2>${service.paragraphs.map(paragraph=>`<p>${escape(paragraph)}</p>`).join('')}<div class="outcomes"><h3>${t('Waar we aan werken','What we work on')}</h3>${service.results.map(result=>`<p>${icon('check')}${escape(result)}</p>`).join('')}</div>${textLink(route('contact',lang)+'?topic='+service.id,t('Bespreek uw vraag met Lex','Discuss your question with Lex'))}</div></div></section>`).join('')}
  ${process({lang})}<section class="small-note"><div class="container"><p>${t('De precieze ondersteuning en afspraken worden per vraagstuk bepaald. Een introductie of gesprek is geen garantie op een opdracht.','The scope of support and the terms are agreed for each project. An introduction or conversation does not guarantee a contract.')}</p></div></section>`;
}
