import { translate, route, servicesFor } from '../content/locale.mjs';
import { icon, eyebrow, button, textLink, portrait, bridgePicture, escape, editorialPhoto } from '../components/ui.mjs';
import { companyStrip, process, faqSection } from '../components/sections.mjs';

export default function home(lang='nl') {
  const t=translate(lang);
  return `<section class="hero" data-parallax aria-labelledby="hero-heading">
    ${bridgePicture({className:'hero-image',eager:true,lang})}<div class="hero-shade" aria-hidden="true"></div>
    <div class="container hero-inner"><div class="hero-copy">${eyebrow(t('Bedrijfsleven ontmoet Defensie & Veiligheid','Where business meets Defence & Security'))}
      <h1 id="hero-heading">${t('Twee werelden.','Two worlds.')}<br><em>${t('Eén verbinding.','One connection.')}</em></h1>
      <p class="hero-lead">${t('Ik help bedrijven zaken te doen met de Defensie- en Veiligheidssector. Met kennis van de praktijk en de juiste mensen aan tafel.','I help companies work with the Defence and Security sector, bringing practical insight and the right people to the table.')}</p>
      <div class="hero-actions">${button(route('contact',lang),t('Laten we kennismaken','Let’s get acquainted'),'light')}${textLink('#expertise',t('Waar ik bij help','How I can help'),'hero-secondary')}</div>
    </div><div class="hero-bottom"><a class="hero-person" href="${route('about',lang)}">${portrait({size:'small',eager:true})}<span><strong>Lex de Lange</strong><small>${t('Oud-militair. Adviseur. Verbinder.','Former serviceman. Adviser. Connector.')}</small></span></a><a class="hero-scroll" href="#expertise">${t('Ontdek Bridge2Connect','Explore Bridge2Connect')} ${icon('down')}</a></div></div>
  </section>${companyStrip(lang)}
  <section class="expertise-intro section-space" id="expertise" aria-labelledby="expertise-heading"><div class="container expertise-overview"><div class="expertise-heading">${eyebrow('Expertise')}<h2 id="expertise-heading">${t('Waar ik uw bedrijf bij kan helpen.','How I can support your company.')}</h2><p>${t('Hoe sluit uw aanbod aan op de sector? Met wie gaat u in gesprek? En hoe brengt u een samenwerking verder? Daar denk en werk ik in mee.','Where does your offering fit? Who should you speak to? How do you take a collaboration forward? I help you work through those questions.')}</p>${editorialPhoto('connectivity',lang)}</div>
    <div class="service-list">${servicesFor(lang).map(service=>`<article class="service-row"><h3>${escape(service.title)}</h3><p>${escape(service.short)}</p>${textLink(route('expertise',lang)+'#'+service.id,t('Meer over '+({sectorinzicht:'sectorinzicht',verbinding:'verbinding',samenwerking:'samenwerking'}[service.id]),'Explore '+({sectorinzicht:'sector insight',verbinding:'connections',samenwerking:'collaboration'}[service.id])))}</article>`).join('')}</div></div></section>
  <section class="about-preview section-space" aria-labelledby="about-heading"><div class="container about-grid">
    <div class="about-intro">${eyebrow('Lex de Lange')}<h2 id="about-heading">${t('Ervaring in Defensie en het bedrijfsleven.','Experience in Defence and business.')}</h2></div>
    <figure class="portrait-frame"><div class="portrait-window">${portrait()}</div></figure>
    <div class="about-copy"><p class="large-paragraph">${t('Ik begrijp beide kanten van de tafel.','I understand both sides of the table.')}</p><p>${t('Als oud-militair en gebrevetteerd commando ken ik Defensie van binnenuit. Vanuit grote en kleine IT-bedrijven heb ik jarenlang met de Defensie- en Veiligheidssector samengewerkt.','As a former serviceman and qualified commando, I know Defence from the inside. I have also spent years working with the Defence and Security sector from within large and small IT companies.')}</p><p>${t('Die ervaring gebruik ik om de vertaalslag te maken tussen wat een organisatie nodig heeft en wat uw bedrijf kan bijdragen.','I draw on that experience to connect what an organisation needs with what your company can contribute.')}</p>${textLink(route('about',lang),t('Meer over Lex','More about Lex'))}</div>
  </div></section>${process({lang})}
  <section class="partner-preview section-space"><div class="container partner-grid"><div>${eyebrow(t('Samenwerking','Collaboration'))}<h2>${t('Samenwerken met de juiste partners.','Working with the right partners.')}</h2></div><div class="partner-copy"><h3>Floru Consulting</h3><p>${t('Vanuit Bridge2Connect werk ik in meerdere trajecten intensief samen met Floru Consulting. Welke ondersteuning nodig is, bepalen we aan de hand van de vraag van uw bedrijf.','Through Bridge2Connect, I work closely with Floru Consulting on a number of projects. The support we provide depends on your company’s question and requirements.')}</p>${textLink(route('network',lang)+'#floru',t('Over deze samenwerking','About this collaboration'))}</div></div></section>
  ${faqSection(lang)}`;
}
