import { site, companies } from '../content/site.mjs';
import { translate, route } from '../content/locale.mjs';
import { escape, safeUrl, eyebrow, textLink, icon } from '../components/ui.mjs';
import { breadcrumbs } from '../components/sections.mjs';

export default function network(lang='nl') {
  const t=translate(lang), partner=safeUrl(site.partnerUrl);
  return `<section class="page-intro section-space"><div class="container">${breadcrumbs(t('Netwerk','Network'),lang)}${eyebrow(t('Netwerk & samenwerking','Network & collaboration'))}<div class="heading-grid page-heading"><h1>${t('Een netwerk binnen<br>en rondom de sector.','A network within<br>and around the sector.')}</h1><p class="large-paragraph">${t('In mijn werk breng ik bedrijven, aanspreekpunten en samenwerkingspartners bij elkaar. Hieronder vindt u een selectie van de bedrijven waarvoor of waarmee ik werk.','My work connects companies, relevant contacts and potential partners. Below is a selection of companies I work for or with.')}</p></div></div></section>
  <section class="network-companies section-space"><div class="container"><div class="heading-grid"><div>${eyebrow(t('Een selectie','A selection'))}<h2>${t('Werkrelaties','Working relationships')}</h2></div><p>${t('Van grote IT-bedrijven tot gespecialiseerde technologiebedrijven: de vraag en de benodigde ondersteuning verschillen per organisatie.','From large IT companies to specialist technology businesses, the questions and support required differ for each organisation.')}</p></div><div class="network-grid">${companies.map(name=>`<article class="network-name"><h3>${escape(name)}</h3></article>`).join('')}</div></div></section>
  <section class="floru-section section-space" id="floru"><div class="container editorial-layout"><div>${eyebrow(t('Samenwerking','Collaboration'))}<h2>Floru Consulting</h2></div><div class="prose"><p class="large-paragraph">${t('Bridge2Connect werkt in meerdere trajecten intensief samen met Floru Consulting.','Bridge2Connect works closely with Floru Consulting on a number of projects.')}</p><p>${t('Door vanuit verschillende perspectieven naar een vraag te kijken, ontstaat een completer beeld. De invulling van de samenwerking volgt het vraagstuk en wat het bedrijf op dat moment nodig heeft.','Looking at a question from different perspectives gives a fuller picture. The form of the collaboration follows the challenge and what the company needs at that point.')}</p><p>${t('Wilt u bespreken welke ondersteuning bij uw organisatie past? Een eerste gesprek met Lex is het vertrekpunt.','To explore which support would suit your organisation, start with a conversation with Lex.')}</p>${partner?`<a class="text-link" href="${escape(partner)}" target="_blank" rel="noopener noreferrer">${t('Naar Floru Consulting','Visit Floru Consulting')} ${icon('diagonal')}</a>`:textLink(route('contact',lang),t('Bespreek de mogelijkheden','Discuss the possibilities'))}</div></div></section>`;
}
