import { resolveContactDelivery } from '../content/contact-delivery.mjs';
import { deliveryPrivacy } from '../components/contact-delivery.mjs';
import { site } from '../content/site.mjs';
import { translate, route } from '../content/locale.mjs';
import { escape, safeUrl, eyebrow } from '../components/ui.mjs';
import { breadcrumbs } from '../components/sections.mjs';

export default function privacy(lang='nl', deliveryOptions) {
  const delivery = resolveContactDelivery(deliveryOptions);
  const t=translate(lang), email=safeUrl(site.email,{email:true});
  const sections=[
    [t('Over deze website','About this website'),t('Deze website is gemaakt voor Bridge2Connect, het bedrijf van Lex de Lange. Vragen over de website kunt u mailen naar','This website was created for Bridge2Connect, the business of Lex de Lange. Questions about the website can be emailed to')+` <a href="${escape(email)}">${escape(site.email)}</a>.`],
    [t('Het contactformulier','The contact form'),delivery.enabled ? deliveryPrivacy(lang) : t('Het formulier stelt een conceptbericht samen in uw browser. De website verstuurt de invoer niet naar een server en bewaart deze niet in een database, cookies of lokale opslag. U bepaalt zelf of u de tekst kopieert of uw eigen mailprogramma opent. Het openen van een mailprogramma is niet hetzelfde als het verzenden van een bericht.','The form prepares a draft message in your browser. The website does not submit your input to a server or store it in a database, cookies or local storage. You decide whether to copy the text or open your own email application. Opening an email application is not the same as sending a message.')],
    [t('Taalkeuze en cookies','Language choice and cookies'),t('De Nederlandse en Engelse versie hebben ieder hun eigen pagina-adres. Er is geen vertaalservice nodig en uw taalkeuze wordt niet met een cookie opgeslagen. De websitecode gebruikt geen analytics, advertentietrackers of ingesloten socialmediafeeds. Afbeeldingen, scripts en stijlen komen van de website zelf; de lettertypen zijn systeemlettertypen.','The Dutch and English versions each have their own page addresses. No translation service is needed, and your language choice is not stored in a cookie. The website code uses no analytics, advertising trackers or embedded social media feeds. Images, scripts and styles are served by the website; fonts are system fonts.')],
    [t('Hosting en bereikbaarheid','Hosting and availability'),t('De website op bridge2connect.nl wordt gehost bij STRATO. Een hostingdienst kan technische gegevens verwerken om de site te leveren en te beveiligen. De website is met de link publiek bereikbaar. De zoekmachine-instelling noindex is geen toegangsbeveiliging. Inhoud en privacy-informatie worden vóór de definitieve bedrijfswebsitepublicatie bevestigd.','The website at bridge2connect.nl is hosted by STRATO. A hosting service may process technical information to deliver and secure the site. Anyone with the link can access this website. The noindex search setting is not access control. Content and privacy information will be confirmed before the final business website launch.')],
    [t('Beeldmateriaal en bedrijfsnamen','Images and company names'),t('Het logo en portret zijn aangeleverd voor dit websiteproject. De brugbanner is een AI-gegenereerde sfeerimpressie, geen foto of nauwkeurige 3D-reconstructie. Het scroll-effect beweegt deze afbeelding; het is geen realtime 3D-scène. De bedrijfsnamen beschrijven opgegeven werkrelaties, geen reviews of gegarandeerde resultaten.','The logo and portrait were supplied for this project. The bridge banner is an AI-generated visual impression, not a photograph or an accurate 3D reconstruction. The scroll effect moves that image; it is not a real-time 3D scene. The company names describe reported working relationships, not reviews or guaranteed results.')],
    [t('Fotografie','Photography'),t('De aanvullende technologiebeelden zijn illustratief en tonen geen klantprojecten of locaties van Bridge2Connect. Foto van de communicatieantenne:','The additional technology images are illustrative and do not show Bridge2Connect client projects or premises. Communications antenna photo:')+' <a href="https://unsplash.com/photos/large-satellite-dish-against-a-blue-sky-FIdxhTGKmps">Bernd Dittrich</a>. '+t('Printplaat:','Circuit board:')+' <a href="https://unsplash.com/photos/green-and-black-circuit-board-LrdVFlk4CJ8">Florian Olivo</a>. '+t('Beide via Unsplash, gebruikt onder de','Both via Unsplash, used under the')+' <a href="https://unsplash.com/license">Unsplash License</a>.'],
  ];
  if (delivery.enabled) {
    sections[2][1] = t('De taalkeuze gebruikt geen cookie. Deze site gebruikt geen analytics of advertentietrackers. De beveiliging van het contactformulier laadt hCaptcha zodra u met het formulier werkt. Die externe dienst verwerkt technische gegevens voor spamcontrole; de website plaatst zelf geen marketingcookies.','The language choice uses no cookie. This site uses no analytics or advertising trackers. Contact-form protection loads hCaptcha when you interact with the form. This external service processes technical information for spam protection; the website itself sets no marketing cookies.') + ' <a href="https://www.hcaptcha.com/privacy">hCaptcha privacy</a>';
  }
  return `<section class="page-intro section-space"><div class="container">${breadcrumbs(t('Privacy','Privacy'),lang)}${eyebrow(t('Website-informatie','Website information'))}<h1>${t('Privacy &<br>website-informatie.','Privacy &<br>website information.')}</h1></div></section>
  <section class="section-space legal-page"><div class="container legal-layout"><aside><p>${t('De werking van deze website en het contactproces.','How this website and its contact process work.')}</p><p>${t('Bijgewerkt: 18 september 2026','Updated: 18 September 2026')}</p></aside><div class="prose">${sections.map(([heading,body])=>`<h2>${heading}</h2><p>${body}</p>`).join('')}<h2>${t('Vragen of correcties','Questions or corrections')}</h2><p><a href="${route('contact',lang)}">${t('Neem contact op met Lex.','Get in touch with Lex.')}</a></p></div></div></section>`;
}
